### PR TITLE
Update travis.yml: Add node 7

### PR DESCRIPTION
**Pull request by pzrq**

### CODE REVIEW

**Comment by imlucas** [comment]
Thanks for adding this! We can just target `7` for now.  Don't need to do both IMO. Looks like Travis is a bit angry, but feel free to merge whenever you're ready.

**Comment by pzrq** [comment]
Thanks @imlucas for the feedback.

Sydney discussed this morning and based on information like this [failed build](https://travis-ci.org/mongodb-js/runner/jobs/238652139) have decided to track that issue as COMPASS-1217.

I'm not sure what to do in this case so will leave it open and rebase and perhaps rethink based on your feedback once COMPASS-1217 is resolved.

**Comment by pzrq** [comment]
Probably related [failing Travis build](https://travis-ci.org/acinader/mongodb-runner-test/builds/196011236), via #119

**Comment by pzrq** [comment]
Closing based on https://github.com/mongodb-js/runner/commit/4ce5f3d28dbc505aa70b09b7ddb8df0474951c0c

**Pull request closed without merging**
