### PR TITLE
Support for Jasmine

### PR DESCRIPTION
**Pull request by flovilmart**
- Makes sure the hooks work correctly on jasmine
- Moved the mocha to testing
- Adds deprecation of mocha path.

---

This change is [Reviewable](https://reviewable.io/reviews/mongodb-js/runner/92)

### CODE REVIEW

**Comment by kangas** [comment]
Fixing the crash under Jasmine makes sense to me.
Deprecating the mocha path seems questionable.

Would it be cleaner if we exposed separate mocha/jasmine paths which expose a shared core?

**Comment by flovilmart** [comment]
they are pretty much the same, and mocha is aliased to testing with a nice little warning prompting to change the paths :)

**Comment by imlucas** [comment]
> back from 🍹 

@flovilmart Thanks!  I was thinking about this before vacation. Would it Be better to move test framework shims into their own modules (such as `mongodb-jasmine` or `mongodb-mocha`) rather than having them as subpath requires? This would allow for safer versioning, better encapsulation, and moving more boilerplate out of [spec/helpers.js](https://github.com/ParsePlatform/parse-server/blob/master/spec/helper.js).

**Comment by flovilmart** [comment]
Yeah maybe, but I'm not a big fan or over modularization :)

**Comment by acinader** [comment]
👍

**Pull request closed without merging**
